### ISSUE TITLE
Change drawer to navigation bar.

### ISSUE THREAD

**Issue by dhzdhd** [RedCape-Studios/flixcard#2]
A drawer is difficult to style and not very user friendly.
As the first page is supposed to be one of games/series/movies, by using drawers it is not easy to identify which you are viewing first.

A navigation bar would be helpful here by showing exactly what page you are on and aesthetically pleasing too.

**Comment by dhzdhd** [comment]
@vaiva-a @rithikaaa03  I would like to know your opinions on this

**Comment by vaiva-a** [comment]
yeah i like that idea !

**Comment by dhzdhd** [comment]
Alright will work on it
