### ISSUE TITLE
A favorites route

### ISSUE THREAD

**Issue by dhzdhd** [RedCape-Studios/flixcard#5]
With the removal of the menu drawer, the menu drawer icon button was also removed from the AppBar.
I included a star icon as a placeholder but I suggest that we can implement a favorites route which is linked to that icon button.

I would like to hear your suggestions

**Comment by dhzdhd** [comment]
Is a placeholder required in the scaffold body or do I leave it empty?

**Comment by vaiva-a** [comment]
it dosent matter we are gonna add it later anyways right.. your choice

**Comment by dhzdhd** [comment]
alright, I think i am going to leave it blank for now
